import type { Metadata } from 'next';
import { Noto_Sans_JP } from 'next/font/google';
import './globals.css';
import '@mantine/core/styles.css';
import {
  ColorSchemeScript,
  mantineHtmlProps,
  MantineProvider,
} from '@mantine/core';
import { HeaderMegaMenu } from '@/components/Header';
import { FooterCentered } from '@/components/Footer';

const notoSansJp = Noto_Sans_JP({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Stulog',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body style={notoSansJp.style}>
        <MantineProvider>
          <HeaderMegaMenu />
          {children}
          <FooterCentered />
        </MantineProvider>
      </body>
    </html>
  );
}
